[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = "0.12.10"
sea-orm-migration = { version = "0.12.10", features = ["sqlx-postgres","runtime-tokio-native-tls"]}
chrono = "0.4.31"
