name: CD

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Create Release 🖋
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
